### ISSUE TITLE
Add instructions for configuring with an IdP like Okta or Google

### ISSUE THREAD

**Issue by mraible** [wi3land/ionic-appauth-ng-demo#1]
I'm trying to make this example work with Okta. I've tried changing `auth.service.ts` to use the following, but it doesn't work.

```ts
authConfig: IAuthConfig = {
  identity_client: '0oak72amybljHLd210h7',
  identity_server: 'https://dev-737523.oktapreview.com/oauth2/default',
  redirect_url: 'http://localhost:8100',
  scopes: 'openid profile offline_access',
  usePkce: false,
  end_session_redirect_url: 'http://localhost:8100'
};
```

As far as I can tell, the logic to set the `authenticated` variable in `AuthGuardService` never completes with these settings.

**Comment by wi3land** [comment]
Hi I apologize I haven't uploaded the readme for this project yet. 

I see you are using local host as the callback.
The project uses [CustomUrlScheme](https://github.com/EddyVerbruggen/Custom-URL-scheme), to complete the authorization callback from the IDP. 

If you look inside the config.xml and the package.json under the custom URL scheme, you will see a property called URL_SCHEME this needs to be set to what ever your callback is going to be. So in my example I'm using myAuthApp://AppAuth as the callball, URL scheme is everything before the ://, so the url_scheme is myAppAuth.

I don't think you can use http://localhost:8100 as http is already a URL scheme. You should be able to set the redirect_url in okta.

I have never used okta before, is the preview sandbox free? If so I can have a play around and try to build you a solution.

I will look at making sure Google authentication is supported also.

**Comment by mraible** [comment]
@wi3land Yes, you can use Okta for free. Just go to https://developer.okta.com/signup/ to create an account.

**Comment by wi3land** [comment]
OK so i have the okta login working, no code changes were required. 

This was my auth Config:
` authConfig : IAuthConfig = {
    identity_client: '0oafz4nzhhqJAb6aP356',
    identity_server: 'https://dev-197427.okta.com/oauth2/default',
    redirect_url: 'com.okta.example://appAuth', 
    scopes: 'openid profile offline_access',
    usePkce: true,
    end_session_redirect_url: 'com.okta.example://endSession',
  }`

And this was my config in Okta:
![image](https://user-images.githubusercontent.com/40289227/55860921-2e6d7900-5b6d-11e9-9f6d-f41f7af44b0a.png)

As I mentioned before you need to change the config.xml:
`   <plugin name="cordova-plugin-customurlscheme" spec="4.4.0">
        <variable name="URL_SCHEME" value="com.okta.example" />
    </plugin>`
and the package.json:
`      "cordova-plugin-customurlscheme": {
        "URL_SCHEME": "com.okta.example",
        "ANDROID_SCHEME": " ",
        "ANDROID_HOST": " ",
        "ANDROID_PATHPREFIX": "/"
      }`

Once this is done you will need to remove packages and plugins folders and build them again. This will add the new custom url scheme to the project.

Hope this helps.

**Comment by mraible** [comment]
@wi3land Thanks for the explanation!

I was able to get things kinda working with the following config:

```ts
private addConfig(){
  if(this.platform.is("cordova")){
    this.authConfig = { 
      identity_client: '0oaft6kwksPlgarMw356', 
      identity_server: 'https://dev-133320.okta.com/oauth2/default', 
      redirect_url: 'com.okta.dev-133320:/callback', 
      scopes: 'openid email profile offline_access',
      usePkce: true, 
      end_session_redirect_url: 'com.okta.dev-133320:/logout', 
    }
  }else{
    this.authConfig = { 
      identity_client: '0oaft6l2biU6Yotr3356', 
      identity_server: 'https://dev-133320.okta.com/oauth2/default', 
      redirect_url: 'http://localhost:8100/implicit/authcallback', 
      scopes: 'openid profile offline_access',
      usePkce: false,
      end_session_redirect_url: 'http://localhost:8100/implicit/endsession', 
    }
  }
}
```

However, when running things in a browser, it fails to return an access token, so the Get User Info fails.

<img width="1477" alt="Screen Shot 2019-04-10 at 8 10 41 AM" src="https://user-images.githubusercontent.com/17892/55886922-db45f700-5b69-11e9-944d-8ab13a6a4992.png">
<img width="1477" alt="Screen Shot 2019-04-10 at 8 11 42 AM" src="https://user-images.githubusercontent.com/17892/55886930-dda85100-5b69-11e9-848b-01b6dbb882b3.png">

When running in iOS Simulator, it works.

Related: do you have any plans to support Capacitor? I've tried capacitor-oauth2, but [have issues with it as well](https://github.com/moberwasserlechner/capacitor-oauth2/issues/34).

**Comment by mraible** [comment]
Now I'm trying to make this work with authorization code flow and PKCE in the browser. Okta supports this flow, but I need to send `response_type=code` rather than `token id_token`. 

I changed my config to be as follows:

```ts
private addConfig(){
  const clientId = '0oak8elkkxfdVahEl0h7';
  const issuer = 'https://dev-737523.oktapreview.com/oauth2/default';
  const scopes = 'openid profile offline_access';
  const responseType = 'code';

  if(this.platform.is("cordova")){
    this.authConfig = { 
      identity_client: clientId, 
      identity_server: issuer, 
      redirect_url: 'com.okta.dev-133320:/callback', 
      scopes: scopes,
      usePkce: true, 
      end_session_redirect_url: 'com.okta.dev-133320:/logout', 
    }
  }else{
    this.authConfig = { 
      identity_client: clientId, 
      identity_server: issuer, 
      redirect_url: 'http://localhost:8100/implicit/authcallback', 
      scopes: scopes,
      usePkce: true,
      response_type: 'code',
      end_session_redirect_url: 'http://localhost:8100/implicit/endsession', 
    }
  }
}
```

But then I get the following error:

```
core.js:15724 ERROR Error: Uncaught (in promise): Error: Invalid auth response string
Error: Invalid auth response string
    at IonicImplicitRequestHandler.push../node_modules/ionic-appauth/lib/implicit-request-handler.js.IonicImplicitRequestHandler.getQueryParams (implicit-request-handler.js:273)
    at IonicImplicitRequestHandler.<anonymous> (implicit-request-handler.js:216)
```

**Comment by wi3land** [comment]
You are still using the IonicImplicitRequestHandler for the code flow.
In the constructor of the auth service i am setting the app auth request handler using the code below
`super(
      (platform.is('cordova')) ? browser : undefined,
      (platform.is('cordova')) ? secureStorage : storage,
      (platform.is('cordova')) ? cordovaRequestor : requestor,
      undefined, undefined,
      (platform.is('cordova')) ? new IonicAuthorizationRequestHandler(browser, secureStorage) : new IonicImplicitRequestHandler(new DefaultBrowser(), storage)
    );`

You need to the 6th parameter to just  

` (platform.is('cordova')) ? new IonicAuthorizationRequestHandler(browser, secureStorage) : new IonicAuthorizationRequestHandler(new DefaultBrowser(), storage)`

**Comment by wi3land** [comment]
Just thought about this again and you would actually not need to specify a at all you could just call:
`super( (platform.is('cordova')) ? browser : undefined, (platform.is('cordova')) ? secureStorage : storage, (platform.is('cordova')) ? cordovaRequestor : requestor);`

This will then infer the default which is the IonicAuthorizationRequestHandler.

**Comment by mraible** [comment]
Wahoo - that worked!

For reference, here's what my constructor looks like:

```ts
constructor(
  requestor: RequestorService,
  cordovaRequestor: CordovaRequestorService,
  secureStorage: SecureStorageService,
  storage: StorageService,
  browser: BrowserService,
  private platform: Platform,
  private ngZone: NgZone,
) {
  super((platform.is('cordova')) ? browser : undefined,
    (platform.is('cordova')) ? secureStorage : storage,
    (platform.is('cordova')) ? cordovaRequestor : requestor);

  this.addConfig();
}
```

Thanks for your help. I really appreciate it!

If I wanted to make this work with Capacitor, do I just need to implement new `browser`, `storage`, and `requestor` services for it?

**Comment by mraible** [comment]
I tried making this same app work in Capacitor since it seems Cordova plugins are supported. I followed the Capacitor instructions [in Ionic's docs](https://ionicframework.com/docs/building/ios). When I run it from Xcode, I get the following stack trace and it fails to launch:

```
Loading network plugin
2019-04-10 14:46:41.205002-0600 App[43041:5752412] CAPKeyboard: resize mode - native
⚡️  Loading app at capacitor://localhost...
Reachable via WiFi
APP ACTIVE
⚡️  [log] - onscript loading complete
To Native Cordova ->  Device getDeviceInfo Device1578464673 ["options": []]
To Native Cordova ->  File requestAllPaths File1578464674 ["options": []]
⚡️  [log] - Angular is running in the development mode. Call enableProdMode() to enable the production mode.
⚡️  [log] - Ionic Native: deviceready event fired after 243 ms
⚡️  [warn] - Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed.
⚡️  [warn] - Install the StatusBar plugin: 'ionic cordova plugin add cordova-plugin-statusbar'
⚡️  [warn] - Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.
⚡️  [warn] - Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen'
To Native Cordova ->  SecureStorage init SecureStorage1578464675 ["options": [SecretStore]]
⚡️  To Native ->  App addListener 52640956
⚡️  WebView loaded
To Native Cordova ->  SecureStorage get SecureStorage1578464676 ["options": [SecretStore, token_response]]
2019-04-10 14:46:41.948282-0600 App[43041:5752480] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011373c6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000110c98ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011373c555 +[NSException raise:format:] + 197
	3   Foundation                          0x00000001106c7475 -[NSBundle initWithURL:] + 87
	4   Foundation                          0x00000001106c7524 +[NSBundle bundleWithURL:] + 45
	5   CordovaPlugins                      0x000000010ef08857 __34+[SAMKeychainQuery errorWithCode:]_block_invoke + 183
	6   libdispatch.dylib                   0x0000000116060db5 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000011606283d _dispatch_once_callout + 66
	8   CordovaPlugins                      0x000000010ef0809c +[SAMKeychainQuery errorWithCode:] + 156
	9   CordovaPlugins                      0x000000010ef078b8 -[SAMKeychainQuery fetch:] + 568
	10  CordovaPlugins                      0x000000010ef098d9 __21-[SecureStorage get:]_block_invoke + 169
	11  libdispatch.dylib                   0x000000011605fd7f _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x0000000116060db5 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x00000001160637b9 _dispatch_queue_override_invoke + 1022
	14  libdispatch.dylib                   0x0000000116071632 _dispatch_root_queue_drain + 351
	15  libdispatch.dylib                   0x0000000116071fca _dispatch_worker_thread2 + 130
	16  libsystem_pthread.dylib             0x00000001164496b3 _pthread_wqthread + 583
	17  libsystem_pthread.dylib             0x00000001164493fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by mraible** [comment]
I tried to get it to work on Android too. It launches the browser OK, but immediately returns to the app (with no login). When I've worked with Android and AppAuth in the past, I had to configure the `build.gradle` to have an `appAuthRedirectScheme`. I tried adding one, but it doesn't seem to help.

```gradle
android {
    defaultConfig {
        ...

        manifestPlaceholders = [
            appAuthRedirectScheme: "com.okta.dev-133320"
        ]
    }
```

FWIW, I forked this repo and created a PR to show how to configure this demo with Okta. https://github.com/mraible/ionic-4-oidc-demo/pull/1.

**Comment by wi3land** [comment]
Hi Mark, 

I saw you information on iOS and android, I have used this library for my production apps and have never had to edit the info.plist to add the url scheme. The cordova plugin [CustomUrlScheme](https://github.com/EddyVerbruggen/Custom-URL-scheme) should be doing that for you.

**Comment by mraible** [comment]
Thanks for the tip @wi3land. It seems like changing the `URL_SCHEME` value in `package.json` has the same effect.

I'm still not able to make things work in Android. I created a new AVD with the following settings.

<img width="1272" alt="Screen Shot 2019-04-11 at 11 10 55 AM" src="https://user-images.githubusercontent.com/17892/55977158-529f8780-5c4b-11e9-9ec6-e641741714c0.png">

When I try to run my app on it with:

```
ionic cordova run android -l
```

It opens the browser when I click sign in, flashes, then redirects back to the app. The logs in Android Studio show the following errors:

```
2019-04-11 11:15:42.602 5814-5869/? E/aljv: Phenotype API error. Event # btxi@e9a23369, EventCode: GET_EXP [CONTEXT service_id=51 ]
    alil: 29505: No config packages for log source, or config package not registered
        at alki.a(:com.google.android.gms@16089040@16.0.89 (100700-239467275):46)
        at alkh.b(Unknown Source:2)
        at aljv.a(:com.google.android.gms@16089040@16.0.89 (100700-239467275):101)
        at aljv.a(:com.google.android.gms@16089040@16.0.89 (100700-239467275):95)
        at zah.run(:com.google.android.gms@16089040@16.0.89 (100700-239467275):27)
        at bgxm.run(:com.google.android.gms@16089040@16.0.89 (100700-239467275):2)
        at rmf.b(:com.google.android.gms@16089040@16.0.89 (100700-239467275):32)
        at rmf.run(:com.google.android.gms@16089040@16.0.89 (100700-239467275):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at rsc.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2019-04-11 11:15:42.602 5814-5869/? E/AsyncOperation: serviceID=51, operation=GetExperimentTokensOperationCall
    OperationException[Status{statusCode=No config packages for log source, or config package not registered, resolution=null}]
        at aljv.a(:com.google.android.gms@16089040@16.0.89 (100700-239467275):109)
        at aljv.a(:com.google.android.gms@16089040@16.0.89 (100700-239467275):95)
        at zah.run(:com.google.android.gms@16089040@16.0.89 (100700-239467275):27)
        at bgxm.run(:com.google.android.gms@16089040@16.0.89 (100700-239467275):2)
        at rmf.b(:com.google.android.gms@16089040@16.0.89 (100700-239467275):32)
        at rmf.run(:com.google.android.gms@16089040@16.0.89 (100700-239467275):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at rsc.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2019-04-11 11:15:42.678 8333-8349/? E/eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
2019-04-11 11:15:42.678 8333-8349/? E/eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
2019-04-11 11:15:42.710 8333-8349/? E/eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
2019-04-11 11:15:42.711 8333-8349/? E/eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
2019-04-11 11:15:42.744 8333-8349/? E/eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
2019-04-11 11:15:42.745 8333-8349/? E/eglCodecCommon: glUtilsParamSize: unknow param 0x000088ef
2019-04-11 11:15:42.791 7506-7547/? E/cr_PackageMetrics: Could not parse UUID 18ED-2A0B
    java.lang.IllegalArgumentException: Invalid UUID string: 18ED-2A0B
        at java.util.UUID.fromString(UUID.java:194)
        at btx.a(PG:17)
        at boN.d(PG:98)
        at boN.a(PG:141)
        at aEC.call(PG:7)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by wi3land** [comment]
Here is the capacitor demo you asked for https://github.com/wi3land/ionic-appauth-capacitor-demo

**Comment by wi3land** [comment]
Also I don't think you can do live reload with Cordova plugins as I believe it isn't native. Remove the -l from the end of your ionic Cordova run Android and see if that works

**Comment by wi3land** [comment]
Hi mark, there has been a lot of questions in this issue, have they all been answered for you? If so can I close this issue?
