### ISSUE TITLE
Openid Configuration

### ISSUE THREAD

**Issue by marcelonnunes** [wi3land/ionic-appauth-ng-demo#10]
I need to set a different url for the Openid-configuration. 

My application does not follow the pattern:
**https: // [base-server-url] /.well-known/openid-configuration**

Where and how can I make this change?

Thanks.

**Comment by wi3land** [comment]
Hi @marcelonnunes,

you can implement your own versions of pretty much any method in the library to swap functionality to how you need it. The method you need to replace is the the getConfiguration method. It is used to get well-known config whenever it is needed.

This method needs to be placed in your class that extends IonicAuth

```
protected async getConfiguration() {
    if (!this.configuration) {
      const fullUrl =  `${this.authConfig.identity_server}/yourconfigendpoint`;
      this.configuration = await this.requestor
                                    .xhr<AuthorizationServiceConfigurationJson>({url: fullUrl, dataType: 'json', method: 'GET'})
                                    .then(json => new AuthorizationServiceConfiguration(json));
    }

    if (this.configuration !== undefined) {
      return this.configuration;
    } else {
      throw new Error('Unable To Obtain Server Configuration');
    }
}
```

**Comment by marcelonnunes** [comment]
Hello @wi3land ,

Thanks a lot for the help. Worked perfectly.  :-)

I have a question regarding the ionic localStorage.

When I run my application in the Chrome browser, the localStorage variable comes with authenticated user data. However, when I run the application on my android phone the localStorage variable is empty. 

What am I doing wrong ?

**Comment by marcelonnunes** [comment]
@wi3land  Thank you for resolving the above question. Worked perfectly. :-)

I have another question. My OAuth server has a peculiarity where I must pass the parameter "Authorization: basic client_id + client_secret" in the header whenever the token request is made. I looked for the library where the endpoint token is called, but there are dozens of places. How can I override this method to change the header when requesting the token?

Thank you very much again.

**Comment by mraible** [comment]
That's not OAuth, that's Basic Authentication. ;)

**Comment by marcelonnunes** [comment]
I would like help to override a method responsible for requesting the token on the server. I identified 3 files that have the "BaseTokenRequestHandler" method that I need to replace because I need to modify the header parameters.

- node_module \ @openid \ appauth \ src \ **token_request_handler.ts**
- node_module \ @openid \ appauth \ built \ **token_request_handler.js**
- node_module \ @openid \ appauth \ built \ app \ **bundle.js**

How can I override this method?

Thanks.

``` 
export class BaseTokenRequestHandler implements TokenRequestHandler {
  constructor(
      public readonly requestor: Requestor = new JQueryRequestor(),
      public readonly utils: QueryStringUtils = new BasicQueryStringUtils()) {}

  private isTokenResponse(response: TokenResponseJson|
                          TokenErrorJson): response is TokenResponseJson {
    return (response as TokenErrorJson).error === undefined;
  }

  performRevokeTokenRequest(
      configuration: AuthorizationServiceConfiguration,
      request: RevokeTokenRequest): Promise<boolean> {
    let revokeTokenResponse = this.requestor.xhr<boolean>({
      url: configuration.revocationEndpoint,
      method: 'POST',
-->headers: {'Content-Type': 'application/x-www-form-urlencoded'}, <-- // Add new headers
      data: this.utils.stringify(request.toStringMap())
    });

    return revokeTokenResponse.then(response => {
      return true;
    });
  }

  performTokenRequest(configuration: AuthorizationServiceConfiguration, request: TokenRequest):
      Promise<TokenResponse> {
    let tokenResponse = this.requestor.xhr<TokenResponseJson|TokenErrorJson>({
      url: configuration.tokenEndpoint,
      method: 'POST',
      dataType: 'json',  // adding implicit dataType
-->headers: {'Content-Type': 'application/x-www-form-urlencoded'}, <-- // Add new headers
      data: this.utils.stringify(request.toStringMap())
    });

    return tokenResponse.then(response => {
      if (this.isTokenResponse(response)) {
        return new TokenResponse(response);
      } else {
        return Promise.reject<TokenResponse>(
            new AppAuthError(response.error, new TokenError(response)));
      }
    });
  }
}
```

**Comment by wi3land** [comment]
Hi @marcelonnunes, 

Create a new class and implement the TokenRequestHandler interface. Add this class to the IonicAuth constructor as the fourth parameter as shown below. 

```
export class AuthService extends IonicAuth  {

  constructor(
    requestor: Requestor,
    storage: StorageBackend,
    browser: Browser,
    private platform: Platform,
    private ngZone: NgZone,
  ) {
    super(browser, storage, requestor, new TokenHeadersHandler(requestor));

    this.addConfig();
  }

....
```

Can you please raise separate issues for your different problems in future, as it makes it hard for referencing and also keeping track of what is happening.
