### ISSUE TITLE
.well-known/openid-configuration appending on identity_server 

### ISSUE THREAD

**Issue by jchri853** [wi3land/ionic-appauth-ng-demo#12]
Hello there, 

I am trying to make this library work for Azure B2C, I am noticing when I apply my identity_server that its appending “.well-known/openid-configuration” at the end. I need this in the url but when it appends it to the very end it’s not in the right order as far what azure is looking for.

Do you have any tips / walkthrough for making this work with azure B2C and where I can modify this code to prevent the .well-known/openid-configuration being appended? 

This plugin is the only one i can find on the web that supports Ionic so thanks in advance for making this.

**Comment by wi3land** [comment]
Please [Look Here](https://github.com/wi3land/ionic-appauth-ng-demo/issues/10#issuecomment-611581278) same question as yours and gives explanation for overriding the configuration request.
