### ISSUE TITLE
Auto Logins after Signing out. 

### ISSUE THREAD

**Issue by quin0234** [wi3land/ionic-appauth-ng-demo#20]
When I Sign Out of my application, the application automatically signs back in again without any input from the user. 

Looks like the the token is being refreshed within Session Storage. But I can't seem to stop this process happening. 

I'm using ionic-appauth 0.7.2

I have the Landing page and Home page set up with identical code to the demo here. 

I also have signout functionality in the app.component.ts as I have a signout button in a menu. 

Can anyone help me. 

Thanks

**Comment by wi3land** [comment]
It sounds like an issue with  your identity server.
The identity server will auto sign the user back in if the users session isn't ended as part of the sign out process server side.
Sign Out the user and delete all cookies related to your identity server, you should see you will get the login page again.

It will be an issue server side.
